language: java
jdk: openjdk8
services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bay_area_covid_19_tracker;'
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root' IDENTIFIED BY 'rootpassword' WITH GRANT OPTION;"

script:
  - mvn clean install -B